

import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import { Anek_Tamil } from 'next/font/google';
import { Toaster } from 'sonner';
import QueryClientProviderContext from './query-client-provider';

const anekTamil = Anek_Tamil({
  subsets: ['latin'],
  variable: '--font-anek-tamil',
});

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} ${anekTamil.variable}  h-full antialiased`}
    >
      <body className="flex flex-col">
        <div className="flex justify-center w-full">
          <div className="w-full max-w-7xl">
            <QueryClientProviderContext>{children}</QueryClientProviderContext>
            <Toaster />
          </div>
        </div>
      </body>
    </html>
  );
}
